server:
  host: "localhost"
  port: 8080
  max_connection_idle: 60
  max_connection_age: 120
  time: 60
  time_out: 30

db:
  driver: "postgres"
  host: "ep-bitter-cell-a4voat0v-pooler.us-east-1.aws.neon.tech"
  port: 5432
  user: "neondb_owner"
  password: "npg_vlJsba5iB2gP"
  name: "user-db"
  ssl: false
  ssl_mode: "require"
  ssl_cert_path: ""

consul:
  host: "localhost"
  port: 8500

jwt:
  access_token_secret: "my_access_token_secret"
  access_token_age: 3600
  refresh_token_secret: "my_refresh_token_secret"
  refresh_token_age: 7200

logger:
  mode: "production"
  disable_caller: false
  disable_stacktrace: false
  encoding: "json"
  level: "info"
  zap_type: "console"
admin:
  email: "thaibao22042k4@gmail.com"
  password: "baothaipassword"
  first_name: "thai"
  last_name: "bao"
  phone_number: "0828537679"
  access_token_secret: "my_access_token_secret"
  access_token_age: 3600
  refresh_token_secret: "my_refresh_token_secret"
  refresh_token_age: 7200
