apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  labels:
    app: redis
spec:
  clusterIP: None  
  selector:
    app: redis
  ports:
    - name: redis-server
      port: 6379
      targetPort: redis-server
    
