server:
  host: localhost
  port: 3000
consul:
  host: localhost
  port: 8500
logger:
  mode: "production"
  disable_caller: false
  disable_stacktrace: false
  encoding: "json"
  level: "debug"
  zap_type: "console"
grpc_service:
  user_service: localhost:8080
