apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-service-config-map
  namespace: ecommerce-app
data:
  config.yaml: |
    rabbitmq:
      endpoint: "rabbitmq-statefulset-0.rabbitmq-headless.ecommerce-app.svc.cluster.local:5672"
      user_name: "admin"
      password: "admin"
      vhost: "my_vhost"
      is_secure: false
    mailer:
      user_name: "banbao22042004@gmail.com"
      password: "yyof qwry hihv deqz"
      mail_host: "smtp.gmail.com"
      mail_port: 465
    logger:
      level: "debug"
      format: "json"
      output: "stdout"