server:
  host: "localhost"
  port: 50051
mongo:
  uri: "mongodb://admin:admin@localhost:27017"
  database: "product_db"
logger:
  mode: "production"
  disable_caller: false
  disable_stacktrace: false
  encoding: "json"
  level: "info"
  zap_type: "console"
jaeger:
  endpoint: "localhost:4317"