server:
  host: "localhost"
  port: 50051
mongo:
  uri: "mongodb+srv://thaibao22042k4:FWSfTBSCEFte8EiY@ecommerce-go.xbph8.mongodb.net/?retryWrites=true&w=majority&appName=ecommerce-go"
  database: "product-db"
logger:
  mode: "production"
  disable_caller: false
  disable_stacktrace: false
  encoding: "json"
  level: "info"
  zap_type: "console"
jaeger:
  endpoint: "localhost:4317"