services:
  api-gateway:
    image: baothaihcmut/api-gateway:v1
    environment:
      - SERVER_HOST=localhost
      - SERVER_PORT=8080
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - consul
    links:
      - consul
    entrypoint:
      - ./main
      - prod
  user-service:
    image: baothaihcmut/user-service:v1
    environment:
      - SERVER_HOST=user-service
      - SERVER_PORT=50051
      - DB_HOST=ep-noisy-poetry-a1d0s029.ap-southeast-1.aws.neon.tech
      - DB_PORT=5432
      - DB_USER=ecommercedb_owner
      - DB_PASSWORD=1tPyUrfn2jlv
      - DB_NAME=ecommercedb
      - DB_SSL=true
      - DB_SSL_MODE=require
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    ports:
      - "3000:50051"
    depends_on:
      - postgres
      - consul
    links:
      - postgres
      - consul
    entrypoint:
      - /bin/sh
      - -c
      - |
        until ./migrate --env=prod --migrationsFolder=./migrations --action=up prod; do
          echo "Migrations failed.  Respawning.." >&2
          sleep 1
        done
        until ./main prod; do
          echo "Server 'user-service' crashed with exit code $?.  Respawning.." >&2
          sleep 1
        done
    networks:
      - healthcheck-network
      - app-network

volumes:
  postgres-data:
  consul-data:
networks:
  healthcheck-network:
  app-network:
