variables:
  GOLANGCI_LINT_VERSION: 'v1.63.4'
  GOLANG_VERSION: '1.23.2'

cache:
  key: modules
  paths:
    - /go/pkg/mod  
  policy: pull-push

before_script:
  - cd users
  - go version 
  - go mod tidy

stages:
  - lint
  - test 
  - build
  - package

lint:
  image: golangci/golangci-lint:$GOLANGCI_LINT_VERSION
  stage: lint
  script:
  - golangci-lint run --issues-exit-code 0 --print-issued-lines=false --out-format code-climate:gl-code-quality-report.json,line-number
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json

test:
  image: golang:$GOLANG_VERSION
  stage: test
  script: 
  - go test -v ./...
  artifacts:
    paths:
      - test-results.xml 
    reports:
      junit: test-results.xml


build:
  image: golang:$GOLANG_VERSION
  script:
    - go build -o ./main cmd/users/main.go
  artifacts:
    paths:
      - users/main



