variables:
  GOLANGCI_LINT_VERSION: 'v1.56.2'

stages:
  - lint
  - build
  - test 
  - package

lint:
  image: golangci/golangci-lint:$GOLANGCI_LINT_VERSION
  stage: lint
  script:
  - golangci-lint run --issues-exit-code 0 --print-issued-lines=false --out-format code-climate:gl-code-quality-report.json,line-number
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json

