// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Address struct {
	Priority int32
	Street   string
	Town     string
	City     string
	Province string
	UserID   uuid.UUID
}

type Admin struct {
	ID                  uuid.UUID
	Email               string
	Password            string
	PhoneNumber         string
	FirstName           string
	LastName            string
	CurrentRefreshToken sql.NullString
}

type Customer struct {
	UserID     uuid.UUID
	LoyalPoint sql.NullInt32
}

type ShopOwner struct {
	UserID           uuid.UUID
	BussinessLicense sql.NullString
}

type User struct {
	ID                  uuid.UUID
	Email               string
	Password            string
	IsShopOwnerActive   sql.NullBool
	PhoneNumber         string
	FirstName           string
	LastName            string
	CurrentRefreshToken sql.NullString
}
